name: Classify JSON Instructions

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - workflows_LLM
    paths:
      - '**.json'

jobs:
  classify-json:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          ignore_whitespace: true
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Find JSON file
        id: find-json
        run: |
          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          FILES=$(echo "$FILES" | tr -s ' ' | sed 's/^ *//;s/ *$//')
          read -ra FILE_ARRAY <<< "$FILES"

          FILE="${FILE_ARRAY[0]}"
          echo "📂 Detected changed JSON file:"
          echo "    $FILE"
          echo "json_file=$FILE" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Classify JSON file
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🚀 Running classification on:"
          echo "    $json_file"
          python classify.py "$json_file"
