name: Validate & Classify Single JSON Change

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - workflows_LLM

jobs:
  validate-json-change:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1
        with:
          ignore_whitespace: true
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Debug changed files
        run: |
          echo "🔍 All changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n'

      - name: Validate only one .json file changed
        run: |
          # Get all changed files from previous step
          FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Split into array
          read -ra FILE_ARRAY <<< "$FILES"
          
          # Filter only .json files
          JSON_FILES=()
          for FILE in "${FILE_ARRAY[@]}"; do
            if [[ "$FILE" == *.json ]]; then
              JSON_FILES+=("$FILE")
            fi
          done
          
          COUNT=${#JSON_FILES[@]}
          
          echo "🔍 Found $COUNT changed JSON file(s):"
          for i in "${!JSON_FILES[@]}"; do
            echo "  [$((i+1))] ${JSON_FILES[$i]}"
          done
          
          if [[ "$COUNT" -ne 1 ]]; then
            echo "❌ PR must change exactly one .json file. Found $COUNT."
            exit 1
          fi
          
          # Export the file path for next steps
          echo "file_path=${JSON_FILES[0]}" >> $GITHUB_ENV
          echo "✅ Passed: Exactly one .json file changed: ${JSON_FILES[0]}"
      

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Classify changed JSON
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Classifying $changed_file"
          python classify.py "$changed_file"
