name: Classify Changed JSON File

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - workflows_LLM
    paths:
      - '**.json'

jobs:
  classify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Find JSON file
        id: find_file
        run: |
          FILE=$(find . -name "*.json" | head -n 1)
          echo "file_path=$FILE" >> $GITHUB_ENV
          echo "Detected JSON file: $FILE"

      - name: Classify file
        env:
          OPENAI_API_KEY: ${{ secrets.OPEN_AI_KEY }}
        run: |
          echo "Classifying $file_path"
          python classify.py "$file_path"
