name: Validate Single JSON Change

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - automate_actions

jobs:
  check-json-change:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46.0.1

      - name: Validate changed files count and extension
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          
          files="${{ steps.changed-files.outputs.all_changed_files }}"
          IFS=',' read -ra FILE_ARRAY <<< "$files"

          count=${#FILE_ARRAY[@]}
          if [ "$count" -ne 1 ]; then
            echo "PR must change exactly one file. Found $count files."
            exit 1
          fi

          file="${FILE_ARRAY[0]}"
          if [[ ! "$file" =~ \.json$ ]]; then
            echo "Changed file must be a .json file. Found: $file"
            exit 1
          fi

          echo "Passed: PR changes exactly one .json file: $file"
