name: Validate Single JSON Change

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - automate_actions

jobs:
  validate-json-change:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.1 (safe version)

      - name: Validate only one .json file changed
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Convert output into array
          IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.all_changed_files }}"
          COUNT=${#FILES[@]}

          if [[ "$COUNT" -ne 1 ]]; then
            echo "PR must change exactly one file. Found $COUNT files."
            exit 1
          fi

          FILE="${FILES[0]}"
          if [[ ! "$FILE" =~ \.json$ ]]; then
            echo "The changed file must be a .json file. Found: $FILE"
            exit 1
          fi

          echo "Passed: One .json file changed: $FILE"
