name: Validate Single JSON Change

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize, reopened]
    branches:
      - main
      - automate_actions

jobs:
  check-json-change:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch changed files
        id: file_check
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;

            const response = await github.rest.pulls.listFiles({
              owner,
              repo,
              pull_number: number,
            });

            const files = response.data.map(file => file.filename);
            console.log("Changed files:", files);

            if (files.length !== 1) {
              core.setFailed(`PR must change exactly one file. Found ${files.length} files.`);
              return;
            }

            const changedFile = files[0];

            if (!changedFile.endsWith('.json')) {
              core.setFailed(`Changed file must be a .json file. Found: ${changedFile}`);
              return;
            }

            console.log(`Passed: PR changes exactly one .json file: ${changedFile}`);
